function Me = FrameMe(XY,A,rho)
% Me = FrameMe(XY,A,rho)
%      Calcul de la matrice M élémentaire pour un  
%      élément FRAME à deux noeuds (x1,y1) (x2,y2)
% XY  : cordonnées des noeuds  XY = [x1,y1; x2,y2]
% A   : section de l'element
% rho : masse volumique de l'élément 
%
% Voir aussi (See also) :    FRAMEM  FRAMEKE  FRAMEFE


[L,c,s] = EltLen(XY);

Me = (rho*A*L/2) * diag([1 1 0 1 1 0]);            % masse concentrée   

%Me = (rho*A*L/78) * diag([39 39 L^2 39 39 L^2]);   % masse diagonale

%Ma =(rho*A*L/6) * [ 2  0  0  1  0  0 ; ...     % masse repartie
%                   0  0  0  0  0  0 ; ...      % activer Ma, Me, R et R'*Me*R
%                   0  0  0  0  0  0 ; ...
%                   1  0  0  2  0  0 ; ...
%                   0  0  0  0  0  0 ; ...
%                   0  0  0  0  0  0 ; ...
%               ];
%
% Avec hermit  ( VOIR PAGE 279)
%LL = L*L;
%Mm = (rho*A*L/420) * [ 0,     0,      0,  0,    0,      0 ; ...
%                       0,   156,   22*L,  0,   54,  -13*L ; ...
%                       0,  22*L,   4*LL,  0, 13*L,  -3*LL ; ...
%                       0,     0,      0,  0,    0,      0 ; ...
%                       0,    54,   13*L,  0,  156,  -22*L ; ...
%                       0, -13*L,  -3*LL,  0,-22*L,   4*LL ; ...
%                   ];
%Me = Mm + Ma;

%R = [ c, s, 0,  0, 0, 0 ; ...
%     -s, c, 0,  0, 0, 0 ; ...
%      0, 0, 1,  0, 0, 0 ; ...
%      0, 0, 0,  c, s, 0 ; ...
%      0, 0, 0, -s, c, 0 ; ...
%      0, 0, 0,  0, 0, 1 ; ...
%    ];

%Me = R' * Me * R ;
%Me =symetrise(Me);
return